spring.application.name=banking-api

spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.order_updates=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

server.error.include-message=never
server.error.include-stacktrace=never

integrations.decolecta.base-url=https://api.decolecta.com
integrations.decolecta.api-key=sk_7214.hsIjXBG4JLBnMcb9jsvyn3BvRhybG3jZ
integrations.decolecta.connect-timeout=3s
integrations.decolecta.read-timeout=5s

security.jwt.issuer=virtual-banking-api
security.jwt.audience=virtual-banking-clients
security.jwt.access-token-ttl=15m
security.jwt.refresh-token-ttl=7d
security.jwt.public-key-location=classpath:keys/jwt-public.pem
security.jwt.private-key-location=classpath:keys/jwt-private.pem
security.jwt.clock-skew=30s
security.password.bcrypt-strength=12